export class MainSteps {
  
  SURVEY = {
		ROUTE: 'SURVEY',
		ANIMATION: {
			SHOW: 'SHOW_SURVEY',
			HIDE: 'HIDE_SURVEY',
			SHOW_LEFT_TO_RIGH: 'SHOW_SURVEY_LEFT_TO_RIGH'
		}
  };
  
  REASON = {
		ROUTE: 'REASON',
		ANIMATION: {
			SHOW: 'SHOW_REASON',
			HIDE: 'HIDE_REASON',
			SHOW_LEFT_TO_RIGH: 'SHOW_REASON_LEFT_TO_RIGH'
		}
	};

	JUSTIFY = {
		ROUTE: 'JUSTIFY',
		ANIMATION: {
			SHOW: 'SHOW_JUSTIFY',
			HIDE: 'HIDE_JUSTIFY',
			SHOW_LEFT_TO_RIGH: 'SHOW_JUSTIFY_LEFT_TO_RIGH'
		}
	};
	
	THANK = {
		ROUTE: 'THANK',
		ANIMATION: {
			SHOW: 'SHOW_THANK',
			HIDE: 'HIDE_THANK',
			SHOW_LEFT_TO_RIGH: 'SHOW_THANK_LEFT_TO_RIGH'
		}
	};

	ANSWERED = {
		ROUTE: 'ANSWERED',
		ANIMATION: {
			SHOW: 'SHOW_ANSWERED',
			HIDE: 'HIDE_ANSWERED',
			SHOW_LEFT_TO_RIGH: 'SHOW_ANSWERED_LEFT_TO_RIGH'
		}
	};

	constructor() { }
}